# Generated by Django 2.2.7 on 2019-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(upload_to='videos'),
        ),
    ]
