# Generated by Django 2.2.7 on 2019-11-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV', '0002_auto_20191116_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(upload_to='media'),
        ),
    ]
