# Generated by Django 2.2.7 on 2019-11-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV', '0003_auto_20191116_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(upload_to=''),
        ),
    ]
